model:
  arch: marinegpt

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True
  freeze_qformer: False

  # Q-Former
  num_query_token: 32

  # Vicuna
  llama_model: "/data/path/LLAMA_model/"
  gemma_model: "/data/path/gemma-2B/"
  model_format: "gemma_model"

  # generation configs
  prompt: ""

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip2_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
